REM DON'T FORGET TO CTRL H FOR mi

start /D "c:\missingness\" cmd /C ""C:\Program Files\R\R-2.13.0\bin\x64\Rterm.exe" --no-save --args 8 1 mi RHOME=c:\missingness TMPDIR=c:\missingness\tmp < c:\missingness\run.models.r > c:\missingness\results\mi-1.rdata"
start /D "c:\missingness\" cmd /C ""C:\Program Files\R\R-2.13.0\bin\x64\Rterm.exe" --no-save --args 8 2 mi RHOME=c:\missingness TMPDIR=c:\missingness\tmp < c:\missingness\run.models.r > c:\missingness\results\mi-2.rdata"
start /D "c:\missingness\" cmd /C ""C:\Program Files\R\R-2.13.0\bin\x64\Rterm.exe" --no-save --args 8 3 mi RHOME=c:\missingness TMPDIR=c:\missingness\tmp < c:\missingness\run.models.r > c:\missingness\results\mi-3.rdata"
start /D "c:\missingness\" cmd /C ""C:\Program Files\R\R-2.13.0\bin\x64\Rterm.exe" --no-save --args 8 4 mi RHOME=c:\missingness TMPDIR=c:\missingness\tmp < c:\missingness\run.models.r > c:\missingness\results\mi-4.rdata"
start /D "c:\missingness\" cmd /C ""C:\Program Files\R\R-2.13.0\bin\x64\Rterm.exe" --no-save --args 8 5 mi RHOME=c:\missingness TMPDIR=c:\missingness\tmp < c:\missingness\run.models.r > c:\missingness\results\mi-5.rdata"
start /D "c:\missingness\" cmd /C ""C:\Program Files\R\R-2.13.0\bin\x64\Rterm.exe" --no-save --args 8 6 mi RHOME=c:\missingness TMPDIR=c:\missingness\tmp < c:\missingness\run.models.r > c:\missingness\results\mi-6.rdata"
start /D "c:\missingness\" cmd /C ""C:\Program Files\R\R-2.13.0\bin\x64\Rterm.exe" --no-save --args 8 7 mi RHOME=c:\missingness TMPDIR=c:\missingness\tmp < c:\missingness\run.models.r > c:\missingness\results\mi-7.rdata"
start /D "c:\missingness\" cmd /C ""C:\Program Files\R\R-2.13.0\bin\x64\Rterm.exe" --no-save --args 8 8 mi RHOME=c:\missingness TMPDIR=c:\missingness\tmp < c:\missingness\run.models.r > c:\missingness\results\mi-8.rdata"